name: Test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main # to update code coverage

permissions: # added using https://github.com/nextlinux/secure-workflows
  contents: read
concurrency:
  group: ${{ github.workflow }}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: nextlinux/harden-runner@v2.4.0 # v2.1.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            codecov.io:443
            github.com:443
            registry.npmjs.org:443
            storage.googleapis.com:443
            uploader.codecov.io:443

      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: Install Dependencies
        run: npm install
      - name: Run coverage
        run: npm test -- --coverage
      - uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3.1.4
